william r indicator is added
Hypance/HypanceDataAnalysis pull request #1
Opened 2022-09-17 19:45 UTC by uguray75

2022-09-23 17:08 UTC, ttoygar requested changes
Kodu bir liste alıp liste döndürecek bir şekilde değiştirelim. input içeren kısımları kaldıralım.

2022-09-24 19:30 UTC, ttoygar commented
Yapıyı bir class yapısı haline dönüştürelim.

2022-09-29 23:43 UTC, ttoygar commented
Bu hesapta 14 günlük süre sabit midir? Kullanıcıların farklı süreler kullanarak hesaplamak istemesi mümkün mü?

2022-09-29 23:45 UTC, ttoygar commented
Williams_R fonksiyonunun içindeki docstring'i sınıfın başına taşıyabiliriz. Ayrıca (acelesi yok ama) İngilizceye çevirebilirsek harika olur.

2022-09-30 14:16 UTC, Bahar-K approved these changes

2022-09-30 18:11 UTC, ANL3 approved these changes

2022-09-30 18:20 UTC, hasanboyaci approved these changes

2022-09-30 20:07 UTC, gorkemaltay1 approved these changes

2022-10-01 16:30 UTC, ttoygar approved these changes
Fonksiyonlara annotationlar eklenebilir, ancak bunun acelesi yok, testleri yazarken ekleyebilirsiniz.

2022-10-01 16:51 UTC, ttoygar approved these changes

2022-10-01 17:16 UTC, merged