Adx
Hypance/HypanceDataAnalysis pull request #114
Opened 2023-02-13 20:25 UTC by Bahar-K

ADX indicator is added

2023-02-15 09:58 UTC, uguray75 reviewed
adx uzun bir liste değerimi döndürmeli yoksa sadece float mı bana float değer dondürmeli gibi geldi

2023-02-15 09:58 UTC, uguray75 commented on hyta/adx.py
> +        return adx_data
```suggestion
        # Compute the directional movement (DX) data using the high, low and close prices of the security.
        dx_data1 = DX(high=self.high,low=self.low,close=self.close)
        dx_data = dx_data1.dx()
        
        # Compute the mean of DX values for the first 14 to 27 days.
        dx_mean = dx_data[14:27].mean()
        
        # Initialize a list with first ADX value as NaN, and the second value as the average DX value.
        adx_data = [np.nan,dx_mean]
        
        # Compute the remaining ADX values for the period.
        for i in range(27, len(dx_data)):
            adx_result = ((adx_data[-1] * 13) + dx_data[i]) / 14
            adx_data.append(adx_result)
    
        return adx_data
```

2023-02-15 10:42 UTC, Bahar-K commented on hyta/adx.py
> +        return adx_data
Tek bir değer döndürmemeli ADX excel dosyasına bakabilirsin oradaki değerler gibi döndürmeli.

2023-03-12 19:05 UTC, uguray75 reviewed
yorum satırı yok

2023-03-12 19:06 UTC, uguray75 requested changes
Daha anlaşılabilir olması için yorum satırı olsa daha iyi olur

2023-03-12 19:10 UTC, ttoygar approved these changes

2023-03-22 17:57 UTC, ttoygar approved these changes

2023-03-22 17:57 UTC, merged