CCI is added as a new branch
Hypance/HypanceDataAnalysis pull request #115
Opened 2023-02-17 14:30 UTC by Esra07

CCI is added as a new branch

2023-02-18 15:02 UTC, ttoygar requested changes

2023-02-18 15:02 UTC, ttoygar commented on hyta/cci.py
> +        df['MAD'] = df['TP'].rolling(20).apply(lambda x: np.median(np.absolute(x - np.median(x))))
25'inci ve 26'ncı satırlar kaymış. Indent hatası veriyor.

2023-02-18 15:02 UTC, ttoygar commented on Tests/test_cci.py
> +        self.assertAlmostEqual(self.cci.MAD(tp)[23], self.data["MAD"][23])
CCI.xls dosyasında bir "MAD" sütunu yok. MD olarak yazılmış olabilir mi?

2023-02-18 15:24 UTC, Esra07 commented on hyta/cci.py
> +        df['MAD'] = df['TP'].rolling(20).apply(lambda x: np.median(np.absolute(x - np.median(x))))
Düzelttim.

2023-03-01 18:13 UTC, ttoygar approved these changes

2023-03-01 18:14 UTC, hasanboyaci approved these changes

2023-03-01 18:15 UTC, Bahar-K approved these changes

2023-03-01 18:54 UTC, merged