macd indicator is added
Hypance/HypanceDataAnalysis pull request #2
Opened 2022-09-17 20:55 UTC by ANL3

2022-09-22 12:53 UTC, ttoygar requested changes
Fonksiyonu .py uzantılı bir dosyaya kopyalayıp o dosyayı buraya ekleyelim. Interactive PYthon NoteBook uzantılı bir dosyayı kullanmamız mümkün değil.

2022-09-29 20:35 UTC, hasanboyaci reviewed
değişken isimlerini ve commentleri Türkçe yapabilirsen güzel olur bence. eline sağlık

2022-09-29 20:35 UTC, hasanboyaci commented on Indicators/macd.py
> +path=r"/Users/anilmehmetuyar/Downloads/MACD-Data.xlsx"
bu kısımlar kaldırılmalı. çünkü datayı başka bir yerden alacağız

2022-09-29 23:47 UTC, ttoygar commented
Mümkünse bütün değişken isimlerini, docstringleri ve commentleri İngilizce yazmayı tercih etmeliyiz.

2022-09-29 23:51 UTC, ttoygar requested changes
Sondaki boşlukları da kaldırabiliriz.

2022-09-29 23:53 UTC, ttoygar reviewed
Kod içerisindeki 13 ve 26 günlük süreler sabit midir? Kullanıcının bu hesabı farklı gün değerleri ile isteme ihtimali var mı?

2022-09-30 16:53 UTC, ANL3 commented
> Kod içerisindeki 13 ve 26 günlük süreler sabit midir? Kullanıcının bu hesabı farklı gün değerleri ile isteme ihtimali var mı?

"En sık kullanılan değerler, uzun EMA terimi için 26 gün ve kısa EMA terimi için 12 gündür, ancak işlemcinin tercihidir. Sinyal Hattı için hangi dönem uzunluğu EMA'nın kullanılacağını seçebilir, ancak 9 en yaygın olanıdır."

Yukarıdaki bilgiler tüm kaynaklar için ortak değiştirilebilir ancak yaygın kullanım olarak tüm kaynaklarda EMA için 12-26, Signal için 9 tercih edilmiştir. Excel üzerinde de bu veriler kullanılmıştı. Ama burayı tercihe bağlı hale getirebilirim sizin de onayınızla.

2022-09-30 20:06 UTC, gorkemaltay1 approved these changes

2022-10-01 16:13 UTC, ttoygar commented
> > Kod içerisindeki 13 ve 26 günlük süreler sabit midir? Kullanıcının bu hesabı farklı gün değerleri ile isteme ihtimali var mı?
> 
> "En sık kullanılan değerler, uzun EMA terimi için 26 gün ve kısa EMA terimi için 12 gündür, ancak işlemcinin tercihidir. Sinyal Hattı için hangi dönem uzunluğu EMA'nın kullanılacağını seçebilir, ancak 9 en yaygın olanıdır."
> 
> Yukarıdaki bilgiler tüm kaynaklar için ortak ancak değiştirilebilir. Yaygın kullanım olarak tüm kaynaklarda EMA için 12-26, Signal için 9 tercih edilmiştir. Excel üzerinde de bu veriler kullanılmıştı. Ama burayı tercihe bağlı hale getirebilirim sizin de onayınızla.

Öyle yapalım. Bu değerleri default değerler olarak besleyelim. Kullanıcı özel bir değer vermezse bu değerlerle hesaplarız.

2022-10-01 16:53 UTC, ttoygar requested changes

2022-10-01 16:53 UTC, ttoygar commented on Indicators/macd.py
> +print(MACD(data_close).MovingAverageConvergenceDivergence())
```suggestion
```

Bu satırı kaldıralım. Bu dosyayı çalıştırarak ekrana bir değer yazdırmayacağız. İndikatörler bir paket içerisinden import edilecekler.

2022-10-08 21:23 UTC, gorkemaltay1 commented on hyta/macd.py
> +    def Signal(self) -> list:
anıl

2022-10-11 13:21 UTC, Esra07 approved these changes

2022-10-12 14:33 UTC, uguray75 approved these changes

2022-10-12 17:10 UTC, ttoygar approved these changes

2022-10-12 17:15 UTC, merged