bollinger indicator is added
Hypance/HypanceDataAnalysis pull request #20
Opened 2022-09-24 18:39 UTC by hasanboyaci

bollinger pull request

2022-09-24 19:15 UTC, ttoygar requested changes
plot ve main fonksiyonlarını kaldıralım.

2022-09-24 19:15 UTC, ttoygar commented on Indicators/bollinger.py
> +df = pd.read_excel("Bollinger-Bands-Copied.xls")
Bu satırı kaldıralım.

2022-09-30 00:06 UTC, ttoygar reviewed
Bollinger Bands hesaplanırken 20 gün sabit bir süre midir? Kullanıcının farklı günler kullanarak hesaplamak istemesi gibi bir durum söz konusu olabilir mi?

2022-09-30 18:09 UTC, ANL3 reviewed
Güzel ve temiz görünüyor. Ben de rolling komutunu ve pandası daha detaylı incelemeliyim. Sondaki boşluklar temizlenebilir. Tebrikler.

2022-09-30 18:19 UTC, hasanboyaci commented
> Bollinger Bands hesaplanırken 20 gün sabit bir süre midir? Kullanıcının farklı günler kullanarak hesaplamak istemesi gibi bir durum söz konusu olabilir mi?

Genel olarak 20 günlük hareketli ortalama ve yükseliş/düşüş uzaklığı için de +2/-2 standart sapma kullanılıyor. Hareketli ortalama günü değiştirilebilir, ancak buna bağlı standart sapma oranının da değiştirilmesi gerekir. İsterseniz buna uygun bir şekle çevirebilirim ya da ileride uygulayacağımız strateji tam belli olunca güncelleme yapabilirim.

2022-09-30 20:04 UTC, gorkemaltay1 reviewed
Sinyal veriminden emin olmamakla birlikte genel bağlamda kod güzel. Reviewim de olduktan sonra problem kalmaz gibi. Tebrikler.

2022-09-30 20:04 UTC, gorkemaltay1 commented on Indicators/bollinger.py
> +    return plt.show()
Sanırım bize lazım olan kısım plot'tan ziyade çıkacak sonuçları list şeklinde döndürmek. O yüzden plotlanan kısımlar kalkabilir.

2022-09-30 20:40 UTC, gorkemaltay1 commented on Indicators/bollinger.py
> +    return plt.show()
> Teşekkür ediyorum, kodun son halinde plot ve signal kısımlarını kaldırmıştım. Galiba ilk yüklediğimi yorumlamışsın sen

fark etmemişim evet, yenisine baktım çok güzel. tebrik ederim

2022-09-30 20:40 UTC, gorkemaltay1 approved these changes

2022-10-01 12:26 UTC, uguray75 approved these changes

2022-10-01 16:15 UTC, ttoygar commented
> 

Şimdilik böyle kalsın. Daha fazla ertelemeyelim. İleride nasıl olsa bu indikatörlere test yazacağız, o zaman tekrar ele alırız bu konuyu.

2022-10-01 16:26 UTC, ttoygar approved these changes

2022-10-01 17:08 UTC, merged