updating moving average
Hypance/HypanceDataAnalysis pull request #21
Opened 2022-09-24 19:38 UTC by gorkemaltay1

class mantığına uygun olarak yapıldı.

2022-09-26 21:48 UTC, ttoygar requested changes
Güzel bir çalışma olmuş. Tebrikler.  Commentlerinizi İngilizceye çevirmeyi unutmayın. Ayrıca satırı commentlerle çok uzatmayı istemeyiz. Buradaki best practceler için pep8 dokümantasyonuna bakabilirsiniz.

2022-09-26 21:48 UTC, ttoygar commented on Indicators/dpo.py
> +    def yazdir(self): #liste döndürecek yazdirma fonksiyonu, bu çağırılacak.
Bu fonksiyonun adını İngilizceye çevirelim. DPO sınıfından türetilecek nesnenin bu fonksiyonu obj.fonksiyon_ismi() şeklinde çağıracağını göz önünde bulunduralım.

2022-09-26 21:48 UTC, ttoygar commented on Indicators/dpo.py
> +        return periodCloses
Bu iki satırda periodCloses değişkenini hafızaya almamıza gerek yok. np.array(tempArr)'ı direkt olarak döndürebiliriz.

2022-09-26 21:48 UTC, ttoygar commented on Indicators/dpo.py
> +    def __init__(self,arr:list,period:int=4) -> None: #gereken inputlar: dataset(array),period(int)
arr argümanı daha iyi isimlendirilebilir sanırım. Bu fonksiyonun nasıl kullanıldığını, hangi datayı buraya göndermesi gerektiğini bilmeyen bir kişinin kodunuzu incelediğini düşünün. Bu kişinin ilk bakışta hangi datayı göndermesi gerektiğini anlayabilmesi için arr yerine ne yazardınız?

2022-09-27 05:28 UTC, gorkemaltay1 commented on Indicators/dpo.py
> +    def __init__(self,arr:list,period:int=4) -> None: #gereken inputlar: dataset(array),period(int)
Teşekkürler hocam. Düzelttim :)

2022-09-29 13:08 UTC, Bahar-K approved these changes
Yorum kısımları ingilizceye çerilmeli.

2022-09-30 00:13 UTC, ttoygar requested changes
Commentleri İngilizceye çevirip pep8 uyumlu hale getirirsek işimiz tamam.

2022-09-30 00:13 UTC, ttoygar commented on Indicators/dpo.py
> +    def print(self): #liste döndürecek yazdirma fonksiyonu, bu çağırılacak.
print() standart fonskiyonunu ezmeyelim. Bu fonksiyona farklı bir isim vermek daha uygun olur. Oluşmakta olan uygulama için diğer arkadaşların PR'larına bakabilirsiniz.

Ayrıca, bu fonksiyon mevcut halinde bir liste değil bir numpy array döndürüyor. Gözden kaçmasın.

2022-09-30 00:15 UTC, ttoygar requested changes

2022-09-30 00:15 UTC, ttoygar commented on Indicators/dpo.py
> +        return np.array(tempArr)
Şimdi tekrar bakınca periodCloses isminin vurgulanmasının kodun okunmasını kolaylaştırdığını farkettim. İlk uygulamanız büyük ölçüde benim yönlendirmemden daha doğru. Eski haline getirebilirsek harika olur.

2022-09-30 05:56 UTC, gorkemaltay1 commented on Indicators/dpo.py
> +        return np.array(tempArr)
Hepsi halledildi hocam. Çok teşekkür ederim.

2022-09-30 20:22 UTC, ANL3 approved these changes

2022-10-01 16:23 UTC, ttoygar requested changes
docstringlerle ilgili iki ufak değişikliği uygulayabilirsek her şey tamam.

2022-10-01 16:23 UTC, ttoygar commented on Indicators/dpo.py
> +    def __init__(self,dataset:list,period:int=4) -> None: #required input: dataset(array),period(int)
```suggestion
    #required input: dataset(array),period(int)
    def __init__(self, dataset:list, period:int=4) -> None: 
```

2022-10-01 16:23 UTC, ttoygar commented on Indicators/dpo.py
> +    def dpo(self): #Starting function, it returns a list.
```suggestion
    #Starting function, it returns a list.
    def dpo(self): 
```

2022-10-01 16:23 UTC, ttoygar commented on Indicators/dpo.py
> +    def __init__(self,dataset:list,period:int=4) -> None: #required input: dataset(array),period(int)
pep8 uyumu için ufak bir değişiklik.

2022-10-01 16:23 UTC, ttoygar commented on Indicators/dpo.py
> +        return periodCloses
Tekrar düşününce böyle kalması okunabilirlik açısından daha doğru.

2022-10-01 17:18 UTC, ttoygar approved these changes

2022-10-01 17:18 UTC, merged