cmf.py is added
Hypance/HypanceDataAnalysis pull request #22
Opened 2022-09-24 19:43 UTC by Bahar-K

2022-09-24 19:44 UTC, ttoygar requested changes

2022-09-24 19:44 UTC, ttoygar commented on Indicators/cmf.py
> +        print(CMF)
Bu satırı kaldıralım.

2022-09-27 14:00 UTC, ttoygar requested changes
Başlangıçtaki excel okuma ve sütunları ayırma kısmını tamamen kaldırabiliriz. 

Sonda for döngüsü kullanmadan bir çözüm üretebilir miyiz? Her koşulda son işlemleri (for altındaki) de sınıf içerisinde kendi fonksiyonu altında toplayalım. 

En sondaki print'i de kaldıralım.

2022-09-29 11:20 UTC, uguray75 reviewed
4-9 arası silinebilir.

2022-09-29 11:20 UTC, uguray75 commented on Indicators/cmf.py
> +    data_name = 'cs-cmf.xls'
```suggestion
    data_name = 'cs-cmf.xls'
    data = pd.read_excel(data_name)
    # Column adlarını düzeltme
    data.columns.values[4] = "MF_Multiplier"
    data.columns.values[6] = "MF_Volume"
    data.columns.values[7] = "20_period_CMF"
```
bize gelen veri excel dosyasından değilde dışarıdan geleceği için 4-9 arası gerek yok silebilirsin

2022-09-29 20:36 UTC, hasanboyaci approved these changes

2022-09-30 00:24 UTC, ttoygar requested changes
Fonksiyon docstringlerinin başındaki 1. 2. 3. sayaçlarını kaldırabilirsiniz. 

Son olarak, Sınıfa bu sınıfın hangi indikatörü hesapladığına dair bir docstring ekleyebilirseniz işimiz tamam.

2022-09-30 00:24 UTC, ttoygar commented on Indicators/cmf.py
> +        result1 = money_flow_multiplier(data.loc[:,"Close"],data.loc[:,"Low"],data.loc[:,"High"])
result1 yerine money_flow_multiplier için yukarıda kullandığınız mfm ismini kullanabilirsiniz.

2022-09-30 00:24 UTC, ttoygar commented on Indicators/cmf.py
> +        result2 = money_flow_volume(result1, data.loc[:, "Volume"])
Aynı şekilde result2 yerine mfv kısaltmasını kullanabilirsiniz.

2022-09-30 20:00 UTC, gorkemaltay1 approved these changes

2022-09-30 20:08 UTC, ANL3 approved these changes

2022-10-01 12:23 UTC, uguray75 approved these changes

2022-10-01 16:19 UTC, ttoygar approved these changes
Tebrikler. ^^

2022-10-01 17:55 UTC, merged