Add files via upload
Hypance/HypanceDataAnalysis pull request #23
Opened 2022-09-25 08:36 UTC by esramelikecakir

2022-09-25 08:47 UTC, gorkemaltay1 commented on Indicators/rsi.py
> +data_close = rsi_db["close"]
veri okunan satırlar kaldırılmalı,

2022-09-26 21:57 UTC, ttoygar requested changes
Elinize sağlık. Güzel bir çalışma olmuş. Sadece birkaç ufak düzeltme yeterli. Ayrıca koda dokümantasyon eklemeyi ihmal etmeyelim.

2022-09-26 21:57 UTC, ttoygar commented on Indicators/rsi.py
> +Result = Rsi_counter()
```suggestion
```

2022-09-26 21:57 UTC, ttoygar commented on Indicators/rsi.py
> +Result = Rsi_counter()
Sınıfı burada instantiate etmeyeceğiz. Bu satır kaldırılmalı.

2022-09-26 21:57 UTC, ttoygar commented on Indicators/rsi.py
> +print(Result.rsi_function())
```suggestion
```

2022-09-26 21:57 UTC, ttoygar commented on Indicators/rsi.py
> +print(Result.rsi_function())
Aynı mantıkla burada yazdırmamız da doğru değil. Bu satır da kaldırılmalı.

2022-09-26 21:57 UTC, ttoygar commented on Indicators/rsi.py
> +    def rsi_function(self):
Bu fonksiyonun ismini rsi olarak değiştirebilirsiniz sanıyorum. Paketin convention'u bu yönde gelişiyor. Böylece bu sınıftan instantiate ettiğimiz objeler `obj.rsi()` komutuyla rsi hesaplaması yapar.

2022-09-26 21:57 UTC, ttoygar commented on Indicators/rsi.py
> +data_close = rsi_db["close"]
Datayı düzenleyip fonksiyonlara besleyecek bir ana fonksiyon yazacağız. Datanın düzenlenmesi bu fonksiyon içinde çözülecek. Dolayısıyla burada veri okuyan veya düzenleyen satırlar bulunmamalı.

2022-09-28 18:21 UTC, ttoygar requested changes

2022-09-28 18:21 UTC, ttoygar commented on Indicators/rsi.py
> +    def __int__(self, data_close, total_gain, total_loss):
```suggestion
    def __init__(self, data_close, total_gain, total_loss):
```

2022-09-28 18:24 UTC, merged