Mfi
Hypance/HypanceDataAnalysis pull request #29
Opened 2022-10-02 20:28 UTC by Bahar-K

mfi is added

2022-10-08 17:05 UTC, ANL3 approved these changes

2022-10-08 21:21 UTC, gorkemaltay1 commented on Indicators/mfi.py
> +    def typical_price(high,low,close) -> pd.Series:
bahar

2022-10-16 13:57 UTC, gorkemaltay1 approved these changes

2022-10-17 17:48 UTC, uguray75 approved these changes

2022-10-17 22:32 UTC, Esra07 approved these changes

2022-10-26 17:31 UTC, ttoygar requested changes
setUp içerisindeki fonksiyonları test fonksiyonlarının içine taşıyabiliriz. Böylece bu fonksiyonlar ilgili olmadıkları testler için çalıştırılmazlar.

2022-10-26 17:33 UTC, ttoygar commented on Tests/test_mfi.py
> +        self.assertAlmostEqual(self.typical_price[1],self.data["Typical Price"][1])
Farklı bir sütun için bir tane daha test ekleyebiliriz.

2022-10-26 17:41 UTC, ttoygar commented on Tests/test_mfi.py
> +        self.assertIsInstance(self.money_ratio,pd.Series)
Burada money ratio için yakınsayan bir değeri de test edebiliriz.

2022-10-29 17:26 UTC, ttoygar approved these changes

2022-10-29 17:28 UTC, ttoygar requested changes
excel dosyasının içinde bulunfuğu klasör Files > files olmalı

2022-10-29 17:28 UTC, ttoygar commented on Tests/test_mfi.py
> +        cls.data = pd.read_excel('Files/cs-mfi.1.xls')
```suggestion
        cls.data = pd.read_excel('files/cs-mfi.1.xls')
```

2022-11-28 08:38 UTC, esramelikecakir approved these changes

2022-12-13 20:11 UTC, Bahar-K commented
Mfi branch is closed due to conflict and new branch is oppened.

2022-12-13 20:11 UTC, closed without merging