Stochastic_Oscillator is added
Hypance/HypanceDataAnalysis pull request #4
Opened 2022-09-23 17:15 UTC by Esra07

2022-09-26 22:01 UTC, ttoygar requested changes
Tebrikler. Çok temiz bir çalışma. Commentleri kullanma biçminiz harika.

2022-09-26 22:01 UTC, ttoygar commented on Indicators/Stochastic_Oscillator.py
> +    copy = df.copy()
Dataframe'in bu fonksiyona beslenen haline ihtiyacımız yok aslında. Dolayısıyla buradan copy'i kaldırabiliriz. Ancak datayı bir liste olarak alacağımız için bu kısım zaten değişecek. Şimdilik böyle kalmasında sakınca yok.

2022-09-30 00:04 UTC, ttoygar requested changes
Kodun yeni halinde copy yerine df kullanıyoruz. Gözden kaçmasın. 👍

2022-09-30 00:04 UTC, ttoygar commented on Indicators/Stochastic_Oscillator.py
> +class stochastic_oscillator:
```suggestion
class StochasticOscillator:
```

pep8 uyumunu sağlamak için sınıf isimlerinde CamelCase kullanalım.

2022-09-30 00:04 UTC, ttoygar commented on Indicators/Stochastic_Oscillator.py
> +stochastic_oscillator(list).print()
```suggestion
```

Bu dosyayı direkt olarak çağırmayacak, StochasticOcilliator sınıfını import etmek için kullanacağız.

2022-10-03 08:03 UTC, Esra07 commented on Indicators/Stochastic_Oscillator.py
> +class stochastic_oscillator:
Değişiklik yapıldı.

2022-10-03 08:06 UTC, Esra07 commented on Indicators/Stochastic_Oscillator.py
> +        return copy["%D"]= copy["%K"].rolling(3).mean()
Revize edildi.

2022-10-03 08:09 UTC, Esra07 commented on Indicators/Stochastic_Oscillator.py
> +stochastic_oscillator(list).print()
Revize edildi.

2022-10-06 09:20 UTC, Bahar-K approved these changes

2022-10-13 21:44 UTC, gorkemaltay1 approved these changes
Hatalara beraber bakmıştık zaten, bu haliyle approve edebilirim. Tebrikler

2022-10-17 20:35 UTC, ANL3 approved these changes

2022-10-24 23:42 UTC, ttoygar approved these changes

2022-10-26 17:21 UTC, merged