Test.cmf
Hypance/HypanceDataAnalysis pull request #43
Opened 2022-10-09 20:44 UTC by Bahar-K

2022-10-11 19:20 UTC, Esra07 approved these changes

2022-10-26 18:04 UTC, ttoygar commented on Tests/test_cmf.py
> +        self.cmf_result = cmf_data.cmf()
Buradaki fonksiyonları testlerin içine dağıtabiliriz.

2022-10-29 17:22 UTC, ttoygar requested changes

2022-10-29 17:22 UTC, ttoygar commented on Tests/test_cmf.py
> +        cls.data = pd.read_excel('Files/cs-cmf.xls')
```suggestion
        cls.data = pd.read_excel('files/cs-cmf.xls')
```

2022-10-29 17:24 UTC, ttoygar approved these changes

2022-10-29 17:30 UTC, ttoygar approved these changes

2022-10-29 17:48 UTC, merged