the test of williams r was added
Hypance/HypanceDataAnalysis pull request #44
Opened 2022-10-12 14:31 UTC by uguray75

2022-10-13 11:10 UTC, Esra07 approved these changes

2022-10-13 20:42 UTC, ttoygar requested changes

2022-10-14 08:51 UTC, Esra07 approved these changes

2022-10-16 14:00 UTC, gorkemaltay1 approved these changes

2022-10-18 20:16 UTC, Bahar-K approved these changes

2022-10-26 18:44 UTC, ttoygar requested changes
highs, lowest, closes ve result değerlerini excel'den çekelim.

2022-10-26 18:44 UTC, ttoygar commented on Tests/test_williams_r.py
> +
```suggestion
```

2022-10-26 18:44 UTC, ttoygar commented on Tests/test_williams_r.py
> +        self.assertAlmostEqual(self.result[-1], round(r.WILLIAMS_R(),2))
assertAlmostEqual kullanırken round'a ihtiyacımız yok.

2022-12-14 18:31 UTC, ANL3 approved these changes

2022-12-14 18:35 UTC, ttoygar requested changes

2022-12-14 18:35 UTC, ttoygar commented on Tests/test_williams_r.py
> +        cls.data = pd.read_excel('files/WilliamR.xlsx')
```suggestion
        cls.data = pd.read_excel('Tests/files/WilliamR.xlsx')
```

2022-12-14 18:35 UTC, ttoygar commented on Tests/test_williams_r.py
> +
```suggestion


```

2022-12-14 18:35 UTC, ttoygar commented on Tests/test_williams_r.py
> +
```suggestion
```

2022-12-14 18:35 UTC, ttoygar commented on Tests/test_williams_r.py
> +
```suggestion
```

2022-12-14 18:38 UTC, merged