atr_test is added
Hypance/HypanceDataAnalysis pull request #45
Opened 2022-10-12 17:16 UTC by ANL3

2022-10-14 19:03 UTC, gorkemaltay1 commented on Tests/test_atr.py
> +    def setUp(self):
Toygar hocanın yaptığı yorum burada mıydı emin değilim fakat zaten setUpClass'ta df'yi oluşturuyoruz. Her seferinde tekrardan bu değerleri çağırmak biraz garip geldi. Yani setUpClass içinde tanımlayabilirsin veya hangi result'u kullanacaksan testin içinde onu hesaplatabilirsin.

2022-10-14 22:44 UTC, ttoygar requested changes

2022-10-14 22:44 UTC, ttoygar commented on Tests/test_atr.py
> +    def setUp(self):
Tespitiniz doğru.

Farklı true_value'lar (aslında bütün farklı değerler için) ile de test etmek istiyorsak (ki burada böyle yapıyoruz) testin içinde bu değerleri yeniden tanımlayarak değiştirmeliyiz. Dolayısıyla bu durumda hesapladığımız resultlar da testlerin içinde tanımlanmalı.

Eğer bütün testlerde aynı resultları kullanacaksak (öyle yapmıyoruz) bir kere hesaplamamız yeterli. 

Burada kritik olan, bütün result değerlerinin bütün testler için tekrar tekrar hesaplanması. Örneğin result1 sadece test_tr testinde kullanılıyor ama setUp'ta tanımlayarak diğer testler için de yeniden hesaplıyoruz.

Ayrıca, resultları result1 yerine *mesela* result_tr gibi ait olduğu testin ismini vererek okunabilirliğini artırabiliriz. Tabii ki bu, değeri zaten test_tr'ın içinde hesapladığımız zaman önemini kaybedecek. O durumda result değerlerinin birbirine karışma riski olmayacağı için sadece result ismiyle hesaplamamızda bir sakınca olmayacaktır.

2022-10-15 17:39 UTC, ANL3 commented on Tests/test_atr.py
> +    def setUp(self):
düzenleme yapıldı.

2022-10-16 14:01 UTC, gorkemaltay1 approved these changes

2022-10-17 22:31 UTC, Esra07 approved these changes

2022-10-18 10:50 UTC, esramelikecakir approved these changes

2022-10-18 20:14 UTC, Bahar-K approved these changes

2022-10-22 17:58 UTC, ttoygar approved these changes

2022-10-22 17:59 UTC, merged