Ultimate Oscillator added with tests.
Hypance/HypanceDataAnalysis pull request #49
Opened 2022-10-15 16:53 UTC by gorkemaltay1

2022-10-17 10:48 UTC, ANL3 commented on hyta/uo.py
> +    This module, we calculate 7-periods average with
Burada 7,14,28'e göre yapılan hesaplamalar sabit mi? Başka katlar için de oluşturabilir miyiz?

2022-10-17 12:39 UTC, gorkemaltay1 commented on hyta/uo.py
> +    This module, we calculate 7-periods average with
Yok sabit, UO'nun başka türlü hesaplanması yok. Yani opsiyonel bir periyot seçimi yok.

2022-10-17 14:15 UTC, ANL3 approved these changes

2022-10-17 17:54 UTC, uguray75 approved these changes

2022-10-17 22:32 UTC, Esra07 approved these changes

2022-10-18 10:49 UTC, esramelikecakir approved these changes

2022-10-18 20:02 UTC, Bahar-K approved these changes

2022-10-26 18:35 UTC, ttoygar requested changes
Docstringler fonksiyonların içine alınabilir.

2022-11-29 08:04 UTC, Bahar-K commented on Tests/test_uo.py
> +        test = UO(self.low,self.close,self.high).buyingPressure()
setUp fonksiyonu içerisinde "self.uo_data =UO(self.low,self.close,self.high)" şeklinde tanımlayıp test ettiğin fonksiyonlarda self.uo_data.buyingPressure() şeklinde de yapılabilir.

2022-12-03 10:12 UTC, gorkemaltay1 commented on hyta/uo.py
> +            bp = self.close[i+1] - min(self.low[i+1],self.close[i])
shift komutunu kullanmayı tercih etmiyorum ya böyle yapmak benim için daha iyi oluyor.

2022-12-03 10:19 UTC, gorkemaltay1 commented on Tests/test_uo.py
> +        test = UO(self.low,self.close,self.high).buyingPressure()
çok bir farkı olmadığı için öyle kullanmadım, böyle daha açıklayıcı duruyor.

2022-12-04 16:39 UTC, ttoygar approved these changes

2022-12-04 16:39 UTC, merged