ichimoku cloud indicator and its test were added
Hypance/HypanceDataAnalysis pull request #50
Opened 2022-10-15 17:01 UTC by uguray75

2022-10-16 14:03 UTC, gorkemaltay1 approved these changes
İnanılmaz. Tebrikler.

2022-10-17 10:52 UTC, ANL3 approved these changes

2022-10-17 22:29 UTC, Esra07 approved these changes

2022-10-18 10:48 UTC, esramelikecakir approved these changes

2022-10-18 19:55 UTC, Bahar-K commented on Tests/test_ichimoku_cloud.py
> +        self.assertIsInstance(ic.ichimoku_cloud()[0],float)
Buradaki kodlar tekrar etmiş gibi burada ic.ichimoku_cloud()[0],(ic.ichimoku_cloud()[1] .. için for düngüsü içine alınıp yapılabilir mi?

2022-10-19 15:52 UTC, uguray75 commented on Tests/test_ichimoku_cloud.py
> +        self.assertIsInstance(ic.ichimoku_cloud()[0],float)
sadece 1 değeri test ettiğim için for döngüsü kullanmama gerek yoktu. 44. satır değeri 45. satır tipi test ediyor

2022-10-26 18:55 UTC, ttoygar requested changes
Testleri parçalayabiliriz.

2022-10-26 18:55 UTC, ttoygar commented on Tests/test_ichimoku_cloud.py
> +
```suggestion
```

2022-11-29 07:42 UTC, Bahar-K approved these changes

2022-11-30 18:57 UTC, ttoygar approved these changes

2022-11-30 19:01 UTC, merged