momentum and its test were added
Hypance/HypanceDataAnalysis pull request #51
Opened 2022-10-15 17:09 UTC by uguray75

2022-10-16 14:05 UTC, gorkemaltay1 approved these changes

2022-10-17 10:53 UTC, ANL3 approved these changes

2022-10-17 22:30 UTC, Esra07 approved these changes

2022-10-18 10:49 UTC, esramelikecakir approved these changes

2022-10-18 11:42 UTC, Bahar-K approved these changes

2022-12-14 18:40 UTC, ttoygar requested changes

2022-12-14 18:40 UTC, ttoygar commented on Tests/test_momentum.py
> +    @classmethod
```suggestion

    @classmethod
```

2022-12-14 18:40 UTC, ttoygar commented on Tests/test_momentum.py
> +        del cls.cloeses_list
```suggestion
        del cls.closes_list
```

2022-12-14 18:41 UTC, ttoygar requested changes

2022-12-14 18:41 UTC, ttoygar commented on Tests/test_momentum.py
> +        cls.data= pd.read_excel('files/momentum.xlsx')
```suggestion
        cls.data= pd.read_excel('Tests/files/momentum.xlsx')        
```

2022-12-14 18:42 UTC, ttoygar approved these changes

2022-12-14 18:43 UTC, merged