WMA indicator and its test were added
Hypance/HypanceDataAnalysis pull request #52
Opened 2022-10-15 19:27 UTC by uguray75

2022-10-16 14:06 UTC, gorkemaltay1 approved these changes

2022-10-17 10:56 UTC, ANL3 commented on Tests/test_weighted_moving_average.py
> +        cls.close = [34.5, 34.5, 34.37, 34.56, 34.5, 34.37, 34.31, 34.31, 34.25, 34.37, 34.25, 34.12, 34.25, 34.19, 34.19, 33.94, 34.0, 33.75, 33.75, 34.25, 33.94, 34.25, 34.12, 34.5, 34.12, 34.0, 34
Son iki testte veriler, excel dosyasından okunabilir.

2022-10-17 22:30 UTC, Esra07 approved these changes

2022-10-18 10:48 UTC, esramelikecakir approved these changes

2022-10-18 11:30 UTC, Bahar-K approved these changes

2022-12-14 18:43 UTC, ttoygar approved these changes

2022-12-14 18:44 UTC, ttoygar requested changes

2022-12-14 18:44 UTC, ttoygar commented on Tests/test_weighted_moving_average.py
> +        cls.data = pd.read_excel('files/wma.xlsx')
```suggestion
        cls.data = pd.read_excel('Tests/files/wma.xlsx')
```

2022-12-14 18:44 UTC, ttoygar approved these changes

2022-12-14 18:47 UTC, ANL3 approved these changes

2022-12-14 18:48 UTC, merged