RSI pandas version
Hypance/HypanceDataAnalysis pull request #69
Opened 2022-10-31 12:12 UTC by esramelikecakir

RSI with test by using pandas series.

2022-11-02 11:00 UTC, gorkemaltay1 requested changes

2022-11-02 11:00 UTC, gorkemaltay1 commented on Tests/test_rsi.py
> +    def test_loss_calculator(self):
```suggestion
    def test_rsi(self):
```

2022-11-02 11:00 UTC, gorkemaltay1 commented on Tests/test_rsi.py
> +    def test_loss_calculator(self):
sanırım böyle olmalı.

2022-11-27 14:39 UTC, Bahar-K commented on hyta/rsi.py
> +        for i in range(0, len(close)-1):
" Sum of the difference between the current closes and previous closes" bu kısımlar için DataFrame.shift(1) fonksiyonu kullanılabilir.

2023-03-29 17:49 UTC, ttoygar commented
Closed in favor of branch rsi-fixed

2023-03-29 17:49 UTC, closed without merging