Aroon , aroon test and excel file added
Hypance/HypanceDataAnalysis pull request #71
Opened 2022-11-02 11:28 UTC by esramelikecakir

2022-11-02 11:32 UTC, gorkemaltay1 requested changes

2022-11-02 11:32 UTC, gorkemaltay1 commented on Tests/test_aroon.py
> +         cls.df = pd.read_excel("/Users/esra/Library/Containers/com.microsoft.Excel/Data/Downloads/Aroon.Oscillator.xls")
```suggestion
         cls.df = pd.read_excel("files/Aroon.Oscillator.xls")
```

2022-11-03 12:39 UTC, esramelikecakir commented on Tests/test_aroon.py
> +class TestRSI(unittest.TestCase):
class TestAROON(unittest.TestCase):

2022-11-03 12:40 UTC, esramelikecakir commented on Tests/test_aroon.py
> +class TestRSI(unittest.TestCase):
class TestAroon(unittest.TestCase):

2022-11-30 16:05 UTC, ttoygar requested changes
oscillator adının yazımıyla ilgili birkaç yerde hata var. aroon_oscillator metodunda da sanırım bir hata var.

2023-04-02 19:30 UTC, ttoygar commented
closed in favor of aroon-fixed branch

2023-04-02 19:30 UTC, closed without merging