CCI2
Hypance/HypanceDataAnalysis pull request #76
Opened 2022-12-09 18:17 UTC by Esra07

CCI is updated as CCI2

2022-12-10 17:51 UTC, gorkemaltay1 requested changes

2022-12-10 17:51 UTC, gorkemaltay1 commented on hyta/cci.py
> +  def __init__(self,high,slow,close):
```suggestion
  def __init__(self,high,low,close):
```

2022-12-10 17:51 UTC, gorkemaltay1 commented on hyta/cci.py
> +    df['TP']=(df["High"]+df["low"]+df["Close"])/3
```suggestion
    df['TP']=(df["high"]+df["low"]+df["close"])/3
```

2022-12-14 18:26 UTC, ANL3 approved these changes

2022-12-14 18:27 UTC, ttoygar approved these changes

2022-12-14 18:28 UTC, merged